# Generated by Django 3.0.2 on 2020-03-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finch',
            name='length',
        ),
    ]
