# Generated by Django 3.0.2 on 2020-03-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_finch_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('released', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Finch',
        ),
    ]
