# Generated by Django 3.0.2 on 2020-03-22 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200320_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('medium', models.CharField(choices=[('D', 'Digital'), ('C', 'Compact Disc'), ('V', 'Vinyl')], default='D', max_length=1)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Record')),
            ],
        ),
    ]
