# Generated by Django 3.0.2 on 2020-03-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_listening'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='listening',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='listening',
            name='date',
            field=models.DateField(verbose_name='Last listen'),
        ),
    ]
