# Generated by Django 3.0.2 on 2020-03-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200324_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Concert',
            new_name='Distributor',
        ),
        migrations.RenameField(
            model_name='distributor',
            old_name='venue',
            new_name='website',
        ),
    ]
