# Generated by Django 3.0.2 on 2020-03-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200324_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='distributors',
            field=models.ManyToManyField(to='main_app.Distributor'),
        ),
    ]
